### ISSUE TITLE
Won't install on UBUNTU 14.04

### ISSUE THREAD

**Issue by Blaumut** [IkeC/evo-league#1]
I tried to 'make install' the fiveserver, both the original and the one that's packed here.
The terminal outputs:
setuptools pip failed with error code 2
make: *** [install] Error 1

help?

**Comment by IkeC** [comment]
That info is sparse. Is that the full log?

Maybe try a different virtualenv and/or Python version.

http://stackoverflow.com/questions/23448796/creating-new-virtualenv-1-11-5-failed-with-setuptools-issue
