### ISSUE TITLE
Not kind of an issue, but a question...

### ISSUE THREAD

**Issue by pinfake** [IkeC/evo-league#18]
Hi IkeC, I developed pes6j, you can have a look at my profile and you'll see the whole crap there :)
I don't know why, but I just wanted to port the old crap to go, trying to do things more or less right this time around. 
Just on the way of rebuilding it all, I found that you guys, (my reddwarf friend at the time, most probably) got the encryption mechanism for hashing user cdkeys and passwords and check against them whenever a user logs into the game.
I have zero knowledge of python but i've dived into the code and this is what i found out: seems like when a user registers through the form a md5 hash is made by padding the cdkey with zeroes to 36 bytes long and adding the password ("username-password" in your case), then such thing is sent to a "register" controller which ecb blowfishes it using a very specific cypher key. 
I hoped that would be the same stuff the game client would do when it sends auth info to the server, more specifically bytes [32:48] of the 0x3003 packet body, but it doesn't seem to match here :(
So, please, my question for you is: am I missing something?, did I get it all wrong?, did I get it all right but maybe my go crypt thingies aren't working as expected?, if so, ... should I try the same stuff in python?

I probably should have asked this to dwarf, but I don't know how to contact him, I lost all trace.

So, please, if you know something let me know, thank you a ton in advance!!

**Comment by IkeC** [comment]
Sorry mate, can't really help you with that - that's a part of fiveserver I never changed (or completely understood, for that matter).

The only other person I know who might be able to help is Enda, afaik he runs proevolutionsoccer6.com.

**Comment by pinfake** [comment]
Enda!!, that name ring some bells :), probably the only one that could help me then is reddwarf, but no way I can reach him now. 
Thank you very much for taking the time to answer me IkeC, and great job. I take you ported dwarf's code to python as it was C by the time we were doing our things. I don't really know, but it looks well organized (not like my crap).

Thanks again!

**Comment by pinfake** [comment]
Finally got It, the 0x3001 package was giving a different response on my pes6j server than on sixs, it seems like it was some kind of salf or mutation to the blowfish algorithm, I'm just outputting 16 zeroes as six does and it seems to match now.

Thanks for your time IkeC :)

**Comment by IkeC** [comment]
Great, thanks for the feedback!

**Comment by pinfake** [comment]
Anytime!
