### ISSUE TITLE
Windows Install ?

### ISSUE THREAD

**Issue by themasterz** [IkeC/evo-league#2]
Hello Ike, thank you for all you do,
I actually run my local private server for 15 friends on windows 7.
I had tried to install your release on windows
i had installed webserver with php mysql and others requirements, but my sixserver doesn't works with your release.
Is there a way to use windows sixserver ? or linux is required ? 

Thank by advance

**Comment by IkeC** [comment]
"Doesn't work" is not enough info to find an error. :) Please post log files, error messages and so on.

I've never run this on Windows but there's no reason why it wouldn't work. You can also try to install the plain fiveserver first, there's a Windows HowTo here: https://sites.google.com/site/fiveservercom/win32-howto

**Comment by themasterz** [comment]
Hello,
Sorry for last comment, it's not enough like you say.
I had found where is the problem. It's on sixserver.tac file.
In this file you have the row:
statsData = data6.StatsData(storageController)
but in the sixserver windows server6.tac this row doesn't appear.
When i launch i had this results:

 File "twisted\application\app.pyc", line 631, in run

 File "twisted\scripts\twistd.pyc", line 23, in runApp

 File "twisted\application\app.pyc", line 374, in run

 File "twisted\application\app.pyc", line 439, in createOrGetApplication

-- <exception caught here> ---
 File "twisted\application\app.pyc", line 450, in getApplication

 File "twisted\application\service.pyc", line 400, in loadApplication

 File "twisted\persisted\sob.pyc", line 210, in loadValueFromFile

 File "./etc/server6.tac", line 31, in <module>

exceptions.AttributeError: 'module' object has no attribute 'StatsData'

Failed to load application: 'module' object has no attribute 'StatsData'

Any ideas ?

Thank for your help

MasTerZ

**Comment by IkeC** [comment]
StatsData (defined in Sixserver/lib/fiveserver/data6.py) is a class that is only available in Sixserver, not the original fiveserver.
You can't mix use the server6.tac from fiveserver to run the Sixserver code.

**Comment by themasterz** [comment]
That means  we can't use your ladder with fivesever/sixserver windows release.
So I need to install a linux computer for try.
Last question wich linux release do you use ?
Debian, ubuntu ......
Thank you for your help

**Comment by IkeC** [comment]
I had it running on Debian.

I'm not sure why you think you couldn't use the 'windows release'. In the end it's just an archive with python libraries for Windows and the actual python (*.py) and twistd (*.tac) files. The python/twistd files are exactly the same for Windows, Linux or whatever else, just the environment to run them is platform dependent.

**Comment by themasterz** [comment]
i' m agree with you but that need to compile .py on .pyc cause windows release use .pyc.
I don't know how i can do it.
Maybe use your lib folder ?

**Comment by IkeC** [comment]
I see, the windows release already contains precompiled files. On my environment the files are simply recompiled by twistd on server start.

That windows release seems convenient if you want to run the server as is, but if you ever want to make a change or find an error, you're stuck, so you'll need a more flexible environment sooner or later anyway.

Why don't you download Twisted for Windows and give it a try? http://twistedmatrix.com/trac/wiki/Downloads#Windows

**Comment by themasterz** [comment]
I think i will try with debian ut i already have errors....
I closed this comment and open another.
Thank you
