### ISSUE TITLE
Debian

### ISSUE THREAD

**Issue by themasterz** [IkeC/evo-league#3]
Hello again,
I try to use debian 8 but cause of python2.7 i had lot of errors.
I can write full tutorial for you if you explain me some steps.
I know my questions is from noob:

1- Is there a debian release better for evoleague? (6, 7,...)
I succesfully install apache2, php5 with short tag, phpmyadmin, mysql and db config.
After downloading and untar your files,i put http folder in /var/www/yoursite/http
Login with Admin works fine
i download virtualenv, extract in home folder and install with root privilege with this command:
sudo python2.6 setup.py install
cause python 2.7 i try:
sudo python2.7 setup.py install

2-Where i do put your Sixserver folder?  (home directory?)
3-I had seen you use /opt/sixserver/ folder but i haven't this. I need to create folder?

Sorry for all this questions but i really want try your evo-league

**Comment by IkeC** [comment]
1) No, it shouln't matter.
2) + 3) It's a matter of personal preference. If you use /opt/sixserver/ you probably won't have to adjust as many paths.

**Comment by themasterz** [comment]
Thank you,
Concerning chmod/chown for /opt/sixserver that need what?

**Comment by IkeC** [comment]
That pretty much depends on your setup and how secure you want it. 
755 for the directory should be ok.
