### ISSUE TITLE
./service.sh: line 29: /opt/sixserver/sixserver-env/bin/twistd:  Don't have that file or directory

### ISSUE THREAD

**Issue by kulaka** [IkeC/evo-league#6]
Dear IkeC:
I can install fiveserver0.49,but can't  install sixserver。

 Skipping installation of /root/fsenv/lib/python2.6/site-packages/zope/__init__.py (namespace package)
    Installing /root/fsenv/lib/python2.6/site-packages/zope.interface-3.8.0-py2.6-nspkg.pth
Successfully installed MySQL-python PyYAML Twisted pyOpenSSL pycrypto zope.interface
Cleaning up...

Python-2.6.8，virtualenv-1.7.1.2，sixserver were  installed successfully。

when i thy to run it，this happened

[root@ebs-28727 Sixserver]# ./service.sh
-bash: ./service.sh: no permissions

[root@ebs-28727 Sixserver]# chmod 777 ./service.sh 

[root@ebs-28727 Sixserver]# ./service.sh start
sixserver start...
[root@ebs-28727 Sixserver]# ./service.sh: line 29: /opt/sixserver/sixserver-env/bin/twistd: 
Don't have that file or directory

I don't know how to solve it, I am not good at Linux and programming

i hope you can give me a hand，thank for you help！

**Comment by IkeC** [comment]
Well, does opt/sixserver/sixserver-env/bin/twistd exist or not?

**Comment by kulaka** [comment]
opt/sixserver/sixserver-env/bin/twistd  don't exist
/opt directory  is empty，have nothing

**Comment by kulaka** [comment]
I  solved it,

**Comment by Freederth** [comment]
how did you solve it? i have the same problem.

**Comment by robao23** [comment]
I'm in exactly the same situation.

the web works without problems, I can install sixserver but the same problem occurs when trying to execute it
