### ISSUE TITLE
Questions about the registration

### ISSUE THREAD

**Issue by kulaka** [IkeC/evo-league#7]
Dear IkeC:
In order to establish sixserver, I spent a lot of time to learn how to configure PHP under Linux, now the website is ready, but when registering a new account, an email problem bothering me, I don't know where to set the administrator email to activate the new account. I find the code in a PHP file, isn't it inside the phpmailer - 2.0.2, because I'm not good at PHP code, so can't make any effective change. Can you tell me the code about  email in which PHP file, I will try to configure it. I don't have a good website building experience, but I love pes6, I will go on, until my sixserver can run. But may need some help from you, hope you can give me some technical support! Without you, juce and reddwarf, we pes6 fans can't play pes6ol together. But we don't like Ibrahim, in order to build its web site become a thief, I would never go to their website play pes6! 
Thanks ！
hope your reply！

**Comment by IkeC** [comment]
The problem isn't clear - are you talking about the email from the server to the player with an activation link in it?

The function for that is defined in functions.php:
```
// sends a new user a sign-up mail
function sendActivationLinkMail($toAddress, $playerName, $link) {
	...
	@ mail($toAddress, $subject, $message, $head, $mailconfig);
	...
}
```

So, it is the PHP mail function that's being used. 

http://php.net/manual/en/function.mail.php

That function tries to use /usr/bin/sendmail to send out emails, which may not be installed or properly configured on your system. You may want to configure the mail.log parameter in your php.ini file to see what's happening.

http://php.net/manual/en/mail.configuration.php

**Comment by kulaka** [comment]
Yes, I talking about the email from the server to the player with an activation link in it.
In the beginning, I found the phpmailer - 2.0.2 in the document, I thought the server send mail to player through it. So I don't know, in which files to modify the code, such as SMTP address, username, password. Now, I'll try to configure the sendmail。
thanks a lot!

**Comment by kulaka** [comment]
Oh my god,it's so hard to approve the new players for me.

I can use the mail () function to send mail to my email,and received successfully.In /var/log/maillog

For example:
<?php 
$send = mail('11111KULAKA@gmail.com', 'test', 'hello,world'); 
if($send){ 
echo 'true'; 
}else{ 
echo 'false'; 
} 
?>
I can find something about 11111KULAKA@gmail.com.

when I use another email(eg 22222KULAKA@gmail.com) to register a new account，
I still can't receive an email from sixserver,
in /var/log/maillog, i can't find anything about  22222KULAKA@gmail.com.

In approvePlayers.php  Today's log
I can see

2015-06-20 6:32:44 - INFO --> CheckSimilarAccounts (KULAKA,222.38.24.194,$2y$10$YbfS/wz0Dbe0W6rg.gBHGekPz3lteVH/EQhtBT.og6QMcb01HfyBK,22222KULAKA@gmail.com):  start
2015-06-20 6:32:44 - INFO --> CheckSimilarAccounts (KULAKA,222.38.24.194,$2y$10$YbfS/wz0Dbe0W6rg.gBHGekPz3lteVH/EQhtBT.og6QMcb01HfyBK,22222KULAKA@gmail.com):  access: user=Admin ip=222.38.24.194
2015-06-20 6:32:44 - INFO --> sql: INSERT INTO
weblm_players 
(name, alias, pwd, mail, icq, aim, msn, country, nationality, approved, ip, joindate, activeDate, forum, sendGamesMail, sendDeductMail, sendNewsletter, uploadSpeed, downloadSpeed, message, versions, defaultversion, favteam1, favteam2, serial5, hash5, serial6, hash6, signup) 
VALUES ('KULAKA','Alias','$2y$10$YbfS/wz0Dbe0W6rg.gBHGekPz3lteVH/EQhtBT.og6QMcb01HfyBK', '22222KULAKA@gmail.com','n/a','n/a', 'MSN Messenger', 'Albania', 'Algeria', 'no', '222.38.24.194', '1434781964', '1434781964', 'Group', 'yes', 'no', 'yes', '', '', 'Message', 'H', 'H', '100', '101','', '', 'J52FCN5H7366CPXNYHU7', '', '456edfb556e578debffae6793a39f3e3')
2015-06-20 6:32:44 - INFO --> result: 1
2015-06-20 6:32:44 - INFO --> sendActivation: autoApprove=1
2015-06-20 6:32:44 - INFO --> sendActivation: sql=SELECT mail, name, signup from weblm_players where player_id = '7'
2015-06-20 6:32:44 - INFO --> sendActivation: res=success
2015-06-20 6:32:44 - INFO --> sendActivation: update_result=1

autoApprove=1
res=success
does it mean that an email have already sended to 22222KULAKA@gmail.com
why in /var/log/maillog, i can't find anything about  22222KULAKA@gmail.com.
![111](https://cloud.githubusercontent.com/assets/12582491/8266417/380d3c2a-1760-11e5-85d7-a172c1b90ef6.png)

**Comment by IkeC** [comment]
Check function sendActivationLinkMail in functions.php:
```
@ mail($toAddress, $subject, $message, $head, $mailconfig);
```
You may want to add additional logging here, and maybe remove the *$mailconfig* parameter.

**Comment by kulaka** [comment]
Thank you, I have sent an email successfully
Sixeserver is powerful, but it is also hard to master
In order to use it well, I have to start learning PHP and mysql
